apiVersion: apps/v1
kind: Deployment
metadata:
  name: shorturl-frontend
  namespace: shorturl
  labels:
    app: shorturl-frontend
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: shorturl-frontend 
  template:
    metadata:
      labels:
        app: shorturl-frontend
      annotations:
        deploy-date: "deploy-date-value"
    spec:
      containers:
      - name: shorturl-frontend
        image: bwbwchen/shorturl-frontend
        ports:
        - containerPort: 80
