apiVersion: v1
kind: Service
metadata:
  name: shorturl-frontend-service
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30391
    protocol: TCP
    targetPort: 80
  selector:
    app: shorturl-frontend
